# SPDX-FileCopyrightText: 2026 Matteo Beretta
# SPDX-License-Identifier: GPL-3.0-or-later
"""The style sheet, adapted from the owner's Wheelly guide generator
(Wheelly src/guide/site.py), so the two sites read as one family.

Same tokens, same Ink / Amber / Paper palette, same contrast rules: amber is
never used for running text (2.1:1 on paper), only for small marks and as a
surface; a darker amber carries words. Same class names as Wheelly (.indice,
.passo, .punti, .attenzione, .serve) so a fix in one is easy to carry over.

Added for this site: point labels (beginner / expert / misreading / tip),
photo placeholders with the shot brief, tables, part headings, TBD marks,
the collapsed "More" part of a step, the scorecard and a print style for it.
"""

STYLE = """/* SPDX-FileCopyrightText: 2026 Matteo Beretta
   SPDX-License-Identifier: CC-BY-SA-4.0
   Generated by site/sitegen (style.py): do not edit by hand. */

/* Brand colours as in Wheelly: Ink #16191D, Amber #EFA00B, Paper #F7F6F3.
   Amber is NOT a text colour on light ground (2.1:1): small marks only, and a
   dark amber where words must be read. */
:root {
  --fondo: #f7f6f3; --fondo2: #efece5; --carta: #ffffff;
  --testo: #16191d; --muto: #5f646b; --filo: #e2ded5;
  --accento: #efa00b; --accento-testo: #8a5a06;
  --attenzione: #8a5a06; --attenzione-fondo: #fbf2e2;
  --info-fondo: #e9eef3; --info: #2f5677;
  --pillola: #efece5; --pillola-attiva: #ffffff; --pillola-testo: #50555c;
  --ok: #2e6b3a; --ok-fondo: #e5f1e6; --caldo: #a3361f; --caldo-fondo: #f8e6e1;
  --freddo: #24578f; --freddo-fondo: #e3ecf6;
  --indice: 286px;
  --titoli: "Fredoka", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            Helvetica, Arial, sans-serif;
  color-scheme: light dark;
}
@media (prefers-color-scheme: dark) {
  :root {
    --fondo: #14171a; --fondo2: #1a1e22; --carta: #f7f6f3;
    --testo: #e9ebed; --muto: #98a1aa; --filo: #272c31;
    --accento: #efa00b; --accento-testo: #efa00b;
    --attenzione: #efa00b; --attenzione-fondo: #241d12;
    --info-fondo: #18222c; --info: #9cc3e6;
    --pillola: #1f2428; --pillola-attiva: #343a40; --pillola-testo: #aab2ba;
    --ok: #8fd19b; --ok-fondo: #15251a; --caldo: #f2a48f; --caldo-fondo: #2c1813;
    --freddo: #9cc3e6; --freddo-fondo: #142131;
  }
}

* { box-sizing: border-box; }
html { scroll-behavior: smooth; scroll-padding-top: 1.5rem; }
body {
  margin: 0; background: var(--fondo); color: var(--testo);
  font: 17px/1.62 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
        Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--accento-testo); }
h1, h2, h3 { font-family: var(--titoli); line-height: 1.2; letter-spacing: -0.01em; }
code { font: .88em/1.4 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
       background: rgba(127, 140, 155, .16); padding: .08em .32em; border-radius: 5px;
       overflow-wrap: anywhere; }
code.blk { display: block; white-space: pre; overflow-x: auto; overflow-wrap: normal;
           padding: .55em .8em; margin: .45em 0; }
mark.tbd { background: #ffe58a; color: #16191d; border-radius: 4px; padding: 0 .3em;
           font-size: .92em; font-weight: 600; }

/* A download address not known yet (before the Printables upload): greyed words,
   never a dead link; and the download box of each guide. */
.in-arrivo { color: var(--muto); }
.in-arrivo-nota { color: var(--muto); font-size: .82em; }
.scarica { display: flex; flex-wrap: wrap; align-items: center; gap: .6rem 1.1rem; margin: .9rem 0 .4rem; }
.bottone { display: inline-block; padding: .55em 1.1em; border-radius: 999px; font-weight: 600;
           background: var(--testo); color: var(--fondo); text-decoration: none; }
.bottone:hover { opacity: .88; }
.bottone.spento { background: var(--pillola); color: var(--muto); border: 1px dashed var(--filo);
                  cursor: not-allowed; }

.salta { position: absolute; left: -999px; }
.salta:focus { left: 1rem; top: 1rem; background: var(--fondo); padding: .5rem 1rem; z-index: 2; }

.pagina { display: flex; align-items: flex-start; }

/* ---------------------------------------------------------- the fixed contents */
.indice {
  width: var(--indice); flex: 0 0 var(--indice);
  position: sticky; top: 0; height: 100vh; overflow-y: auto;
  border-right: 1px solid var(--filo); background: var(--fondo2);
  padding: 1.6rem 1.1rem 3rem;
}
.indice summary { display: none; }
/* The brand: the logo (sword through the hexagonal layers) and the word mark in Sora. */
.marchio { display: flex; align-items: flex-start; gap: .7rem; text-decoration: none; color: inherit;
           margin: .2rem .4rem 1.6rem; }
.marchio .logo { display: block; width: auto; height: 3.4rem; flex: none; margin-top: -.37rem; }  /* cross-guard level with the top of the capitals */
.marchio .parola { display: block; font-family: "Sora", var(--titoli); font-weight: 400;
                   font-size: 1.45rem; line-height: 1.1; letter-spacing: -.01em; }
.marchio .parola b { font-weight: 700; }
.marchio span.sotto { display: block; margin-top: .45rem; font-size: .78rem; color: var(--muto);
                      letter-spacing: .09em; text-transform: uppercase; }
.indice ol { list-style: none; margin: 0; padding: 0; }
.indice .gruppo { font-size: .74rem; letter-spacing: .1em; text-transform: uppercase;
                  color: var(--muto); margin: 1.1rem .5rem .3rem; }
.indice nav > ol > .gruppo:first-child { margin-top: 0; }
.indice nav a { display: flex; gap: .6rem; text-decoration: none; color: var(--testo);
                padding: .34rem .5rem; border-radius: 7px; font-size: .93rem; }
.indice nav a:hover { background: rgba(127, 140, 155, .14); }
.indice .num { color: var(--muto); font-variant-numeric: tabular-nums; min-width: 1.1rem; }
.indice .manca > a { color: var(--muto); cursor: default; }
.indice .manca > a:hover { background: none; }
.indice .attuale > a { font-weight: 640; }
.indice .passi { margin: .15rem 0 .8rem 1.75rem; border-left: 1px solid var(--filo); }
.indice .passi a { font-size: .875rem; color: var(--muto); padding: .22rem .55rem; border-radius: 0 7px 7px 0; }
.indice .passi a.qui { color: var(--testo); background: rgba(127, 140, 155, .16);
                       box-shadow: inset 2px 0 0 var(--accento); }
.indice .passi .parte-voce { font-size: .72rem; letter-spacing: .09em; text-transform: uppercase;
                             color: var(--muto); padding: .6rem .55rem .1rem; }
.filtro { margin: 0 0 1rem; }
.filtro input { width: 100%; font: inherit; font-size: .9rem;
                padding: .45rem .7rem; border-radius: 8px; border: 1px solid var(--filo);
                background: var(--fondo); color: var(--testo); }
.filtro input:focus { outline: 2px solid var(--accento); outline-offset: 1px; }
.filtro-vuoto { font-size: .875rem; color: var(--muto); margin: 0 .5rem 1rem; }
.indice .passi.altrove { display: none; }
.indice.filtrando .passi.altrove { display: block; }

/* --------------------------------------------------------------- the text */
main { flex: 1 1 auto; min-width: 0; max-width: 1060px; margin: 0 auto;
       padding: 3.2rem 3.4rem 5rem; }
.briciole { margin: 0 0 .5rem; color: var(--muto); font-size: .82rem;
            letter-spacing: .09em; text-transform: uppercase; }
h1 { margin: 0 0 1rem; font-size: 2.3rem; }
.occhiello { font-size: 1.12rem; color: var(--muto); margin: 0 0 2.2rem; max-width: 62ch; }
.occhiello p { margin: 0 0 .8rem; }

/* callouts at the top of a page or a step: warning (amber) and information (blue-grey) */
.avviso { border-radius: 12px; padding: 1rem 1.2rem; margin: 0 0 1.4rem;
          display: flex; gap: .9rem; align-items: flex-start; max-width: 72ch; }
.avviso p { margin: 0; }
.avviso > div > * + * { margin-top: .55rem; }
.avviso ul { margin: 0; padding-left: 1.15rem; }
.avviso li + li { margin-top: .35rem; }
.avviso-titolo { font-size: 1.05rem; }
.passo .avviso.warn { border-width: 2px; }
.avviso::before { font-size: 1.3rem; line-height: 1.2; flex: none; font-weight: 800; }
.avviso.warn { background: var(--attenzione-fondo); border: 1px solid var(--accento); }
.avviso.warn::before { content: "!"; color: var(--attenzione); width: 1rem; text-align: center; }
.avviso.info { background: var(--info-fondo); border: 1px solid transparent; }
.avviso.info::before { content: "i"; color: var(--info); width: 1rem; text-align: center;
                       font-family: Georgia, serif; font-style: italic; }

.serve { border: 1px solid var(--filo); border-radius: 12px; padding: 1.4rem 1.6rem;
         margin: 1.8rem 0 3.2rem; background: var(--fondo2); }
.serve h2 { margin: 0 0 1.1rem; font-size: .84rem; letter-spacing: .1em;
            text-transform: uppercase; color: var(--muto); }
.due { display: grid; grid-template-columns: 1.35fr 1fr; gap: 1.6rem; }
.due h3 { margin: 0 0 .5rem; font-size: .95rem; }
.due ul { list-style: none; margin: 0; padding: 0; }
.due li { padding: .3rem 0; border-top: 1px solid var(--filo); font-size: .95rem; }
.due li:first-of-type { border-top: 0; }
.due li::before { content: "·"; color: var(--accento-testo); margin-right: .5rem; font-weight: 700; }

h2.parte { font-size: .9rem; letter-spacing: .12em; text-transform: uppercase;
           color: var(--accento-testo); margin: 3.4rem 0 0; padding-bottom: .4rem; }
.passo { padding-top: 2.2rem; border-top: 1px solid var(--filo); margin-bottom: 3rem; }
h2.parte + .passo { border-top-color: var(--accento); }
.passo h2 { display: flex; gap: .85rem; align-items: baseline; margin: 0 0 1.4rem; font-size: 1.42rem; }
.passo h2 a.ancora { color: inherit; text-decoration: none; }
.passo .numero { color: var(--accento-testo); font-size: .95rem; font-weight: 700;
                 letter-spacing: .08em; text-transform: uppercase; white-space: nowrap;
                 padding-top: .25rem; }
.passo .attacco { margin: -.6rem 0 1.2rem; max-width: 70ch; }
.corpo { display: grid; grid-template-columns: minmax(0, 1.32fr) minmax(0, 1fr);
         gap: 2.2rem; align-items: start; }
/* A step without a picture takes the whole column: an empty box beside the
   text reads as a picture that did not load. */
.corpo.solo-testo { grid-template-columns: minmax(0, 1fr); }
.corpo.solo-testo .punti { max-width: 76ch; }
.foto { display: grid; gap: 1.2rem; }
figure { margin: 0; }
/* Photos and clips fill their column in a fixed box (aspect: in the YAML,
   4:3 by default, 16:9 for videos; set inline by render.py) and cover it:
   cropped at the edges, never letterboxed, no frame. The link opens the
   whole image. max-height keeps a tall box from becoming a giant image. */
figure > a { display: block; border-radius: 10px; overflow: hidden; line-height: 0; }
figure img, figure.video video, figure.video iframe {
  display: block; width: 100%; height: auto; aspect-ratio: 4 / 3; max-height: 520px;
  object-fit: cover; object-position: center; border-radius: 10px; }
figure.video video, figure.video iframe { aspect-ratio: 16 / 9; background: #000; border: 0; }
figure > a:focus-visible { outline: 2px solid var(--accento); outline-offset: 2px; }
figcaption { margin-top: .5rem; font-size: .8rem; color: var(--muto); }
figcaption .credito { white-space: nowrap; font-style: italic; }
/* The placeholder for a photo the owner has still to take: the same size a
   photo will have, so the page does not jump when it arrives. */
.segnaposto { aspect-ratio: 4 / 3; max-height: 520px; border: 2px dashed var(--filo); border-radius: 10px;
              display: flex; flex-direction: column; align-items: center; justify-content: center;
              gap: .4rem; padding: 1rem; text-align: center; color: var(--muto);
              background: repeating-linear-gradient(135deg, transparent 0 14px,
                          rgba(127, 140, 155, .07) 14px 28px); }
.segnaposto strong { font-family: var(--titoli); font-weight: 600; font-size: 1rem; }
.segnaposto code { font-size: .78rem; }
.brief { margin-top: .5rem; font-size: .82rem; }
.brief summary { cursor: pointer; color: var(--accento-testo); font-weight: 600; }
.brief p { margin: .4rem 0 0; color: var(--muto); }

.punti { list-style: none; margin: 0; padding: 0; }
.punti li { position: relative; padding: 0 0 .85rem 1.25rem; }
.punti li::before { content: ""; position: absolute; left: 0; top: .62em;
                    width: 6px; height: 6px; border-radius: 2px; background: var(--accento); }
.punti .attenzione { background: var(--attenzione-fondo); border-radius: 8px;
                     padding: .6rem .8rem .6rem 1.9rem; margin-bottom: .85rem; }
.punti .attenzione::before { content: "!"; background: none; color: var(--attenzione);
                             font-weight: 800; width: auto; height: auto;
                             left: .8rem; top: .62rem; }
/* labelled points: the label is a small caps word before the text, so the
   eye that looks only for "Expert" finds them without reading the rest */
.punti .etichetta { display: inline-block; font-size: .7rem; font-weight: 700;
                    letter-spacing: .08em; text-transform: uppercase; border-radius: 5px;
                    padding: .05rem .4rem; margin-right: .45rem; vertical-align: .12em; }
.punti .k-beginner .etichetta { background: var(--ok-fondo); color: var(--ok); }
.punti .k-expert .etichetta { background: var(--info-fondo); color: var(--info); }
.punti .k-misread .etichetta { background: var(--caldo-fondo); color: var(--caldo); }
.punti .k-tip .etichetta { background: var(--fondo2); color: var(--muto); border: 1px solid var(--filo); }
.passo .dopo { margin: .4rem 0 0; max-width: 76ch; color: var(--muto); font-size: .95rem; }

/* "More": the collapsed part of a step. A native <details>, closed by default;
   its summary is a small pill with a chevron: quiet next to the text, but
   clearly a control (44 px tall target, hover and keyboard focus visible). */
.approfondisci { margin: .2rem 0 0; max-width: 76ch; }
.approfondisci > summary {
  display: inline-flex; align-items: center; gap: .55rem; list-style: none; cursor: pointer;
  min-height: 2.75rem; padding: 0 1rem 0 .85rem; border-radius: 999px;
  border: 1px solid var(--filo); background: var(--fondo2); color: var(--accento-testo);
  font-size: .9rem; font-weight: 650; letter-spacing: .01em; user-select: none;
  transition: background-color 160ms ease, border-color 160ms ease; }
.approfondisci > summary::-webkit-details-marker { display: none; }
.approfondisci > summary::before {
  content: ""; width: .45rem; height: .45rem; flex: none; margin-top: -.15rem;
  border-right: 2px solid currentColor; border-bottom: 2px solid currentColor;
  transform: rotate(45deg); transition: transform 160ms ease; }
.approfondisci[open] > summary::before { transform: rotate(-135deg); margin-top: .2rem; }
.approfondisci > summary:hover { border-color: var(--accento); background: var(--attenzione-fondo); }
.approfondisci > summary:focus-visible { outline: 2px solid var(--accento); outline-offset: 2px; }
.approfondisci[open] > summary { margin-bottom: .9rem; }
.approfondisci-corpo { border-left: 2px solid var(--filo); padding: 0 0 .2rem 1.1rem; margin: 0 0 .4rem .9rem; }
.approfondisci-corpo > .attacco { margin: 0 0 .9rem; }
.approfondisci-corpo .avviso { margin-bottom: 1rem; }
.foto-extra { grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); margin: .4rem 0 .6rem; }
.occhiello-piu { margin: -1.4rem 0 2rem; }
/* the pencil sketch of the object beside a guide's intro (page `sketch:`):
   decorative, inline SVG drawn in currentColor, so it follows the theme */
.apertura { display: flow-root; }
.schizzo { float: right; width: 33%; max-width: 33%; margin: -.4rem 0 1rem 2rem; color: var(--muto); opacity: .85; }
.schizzo svg { display: block; width: 100%; height: auto; overflow: visible; }
.schizzo path { vector-effect: non-scaling-stroke; }
/* the page's "Expand all / Collapse all", left of the language pill */
.testata .tutto {
  margin-right: auto; align-self: center; font: inherit; font-size: .88rem; font-weight: 600;
  min-height: 2.75rem; padding: 0 1rem; border-radius: 999px; cursor: pointer;
  border: 1px solid var(--filo); background: var(--pillola); color: var(--pillola-testo); }
.testata .tutto:hover { color: var(--testo); border-color: var(--accento); }
.testata .tutto:focus-visible { outline: 2px solid var(--accento); outline-offset: 2px; }
.testata .tutto[aria-pressed="true"] { background: var(--pillola-attiva); color: var(--testo); }

.tabella { overflow-x: auto; margin: .2rem 0 1.2rem; }
.tabella table { border-collapse: collapse; font-size: .92rem; min-width: 100%; }
.tabella th, .tabella td { text-align: left; padding: .45rem .7rem; border-bottom: 1px solid var(--filo);
                           vertical-align: top; }
.tabella th { font-size: .78rem; letter-spacing: .06em; text-transform: uppercase; color: var(--muto);
              font-weight: 600; }

/* a feature's three states, in the reading steps */
.esiti { display: grid; gap: .5rem; margin: 0 0 1rem; }
.peso { display: inline-block; font-size: .7rem; font-weight: 700; letter-spacing: .08em;
        text-transform: uppercase; border-radius: 5px; padding: .05rem .45rem; margin: 0 0 .5rem; }
.peso-primary { background: var(--info-fondo); color: var(--info); }
.peso-check { background: var(--fondo2); color: var(--muto); border: 1px solid var(--filo); }
.peso-confirms { background: transparent; color: var(--muto); border: 1px dashed var(--muto); }
.esiti div { border-radius: 8px; padding: .5rem .8rem; font-size: .95rem; }
.esiti b.lab { display: block; font-size: .72rem; letter-spacing: .08em; text-transform: uppercase; }
.esiti .ok { background: var(--ok-fondo); } .esiti .ok b.lab { color: var(--ok); }
.esiti .caldo { background: var(--caldo-fondo); } .esiti .caldo b.lab { color: var(--caldo); }
.esiti .freddo { background: var(--freddo-fondo); } .esiti .freddo b.lab { color: var(--freddo); }

.avanti { display: flex; justify-content: space-between; gap: 1rem;
          border-top: 1px solid var(--filo); padding-top: 1.6rem; margin-top: 2rem; }
.avanti a { text-decoration: none; font-weight: 600; }
.avanti span { display: block; font-size: .78rem; color: var(--muto);
               font-weight: 400; letter-spacing: .08em; text-transform: uppercase; }
.avanti a.dopo-link { text-align: right; }

/* ------------------------------------------------ the language switch
   As in Wheelly: real links to the same page in each language, 44 px
   targets. It wraps when there are many languages. */
.testata { display: flex; justify-content: flex-end; margin: -1.6rem 0 1.2rem; }
.lang-switch { display: inline-flex; flex-wrap: wrap; align-items: center; gap: 4px; padding: 4px;
               border-radius: 999px; background: var(--pillola);
               border: 1px solid var(--filo); }
.lang-btn { display: inline-flex; align-items: center; justify-content: center;
            min-width: 2.75rem; min-height: 2.75rem; padding: 0 .75rem;
            border-radius: 999px; color: var(--pillola-testo); font-size: .9rem;
            font-weight: 600; text-decoration: none;
            transition: background-color 180ms ease, color 180ms ease; }
.lang-btn:hover { color: var(--testo); }
.lang-btn.is-active { background: var(--pillola-attiva); color: var(--testo); }
.lang-btn:focus-visible { outline: 2px solid var(--accento); outline-offset: 2px; }
@view-transition { navigation: auto; }
@media (prefers-reduced-motion: reduce) {
  @view-transition { navigation: none; }
  html { scroll-behavior: auto; }
  .lang-btn, .approfondisci > summary, .approfondisci > summary::before { transition: none; }
}

/* ------------------------------------------------------- the list of tests */
.capitoli { list-style: none; margin: 0 0 1rem; padding: 0; }
.capitoli li { border-top: 1px solid var(--filo); }
.capitoli li.gruppo { border-top: 0; font-size: .78rem; letter-spacing: .1em; text-transform: uppercase;
                      color: var(--muto); padding: 1.4rem .3rem .4rem; }
.capitoli a, .capitoli .vuoto { display: flex; gap: 1.1rem; align-items: baseline;
                                padding: .85rem .3rem; text-decoration: none; color: var(--testo); }
.capitoli .vuoto { color: var(--muto); }
.capitoli .num { color: var(--muto); font-variant-numeric: tabular-nums; min-width: 1.6rem; }
.capitoli b { font-weight: 600; }
.capitoli em { font-style: normal; color: var(--muto); font-size: .9rem; }
.capitoli .vuoto b { color: var(--muto); font-weight: 500; }
.nota { color: var(--muto); font-size: .92rem; border-top: 1px solid var(--filo);
        margin-top: 3rem; padding-top: 1.2rem; max-width: 70ch; }

/* ------------------------------------------------------------ the scorecard */
.scheda-strumenti { display: flex; flex-wrap: wrap; gap: .8rem 1.4rem; align-items: center;
                    margin: 0 0 1rem; }
.scheda-strumenti label { font-size: .92rem; }
.scheda-strumenti select, .scheda-strumenti button {
  font: inherit; font-size: .92rem; padding: .4rem .7rem; border-radius: 8px;
  border: 1px solid var(--filo); background: var(--fondo2); color: var(--testo); min-height: 2.5rem; }
.scheda-strumenti button { cursor: pointer; font-weight: 600; }
.legenda { display: flex; flex-wrap: wrap; gap: .4rem 1.2rem; font-size: .88rem; margin: 0 0 1rem; color: var(--muto); }
.legenda b { display: inline-block; min-width: 1.6rem; text-align: center; border-radius: 5px; margin-right: .3rem; }
.scheda { border-collapse: collapse; width: 100%; font-size: .9rem; }
.scheda th, .scheda td { border: 1px solid var(--filo); padding: .35rem .4rem; text-align: center; }
.scheda thead th { font-size: .74rem; letter-spacing: .04em; text-transform: uppercase;
                   color: var(--muto); font-weight: 600; vertical-align: bottom; }
.scheda td.temp input { width: 4.2rem; font: inherit; text-align: center; border: 0;
                        background: transparent; color: var(--testo); }
.scheda td.temp input::placeholder { color: var(--muto); }
.scheda td.voto { font-weight: 700; font-variant-numeric: tabular-nums; }
.scheda tr.migliore td { background: var(--ok-fondo); }
.scheda td.note { min-width: 8rem; }
.cella { width: 2.4rem; height: 2.2rem; border-radius: 6px; border: 1px solid var(--filo);
         background: var(--carta); color: #16191d; font: inherit; font-weight: 700; cursor: pointer; }
.cella[data-v="P"], .legenda .P { background: #cfe8d3; color: #1e4a27; }
.cella[data-v="H"], .legenda .H { background: #f6cfc4; color: #6e2312; }
.cella[data-v="C"], .legenda .C { background: #c9dbf0; color: #173d66; }
.cella[data-v="-"] { background: var(--fondo2); color: var(--muto); }
/* pressure advance: L (too low, bulge) warm like "too hot", H (too high, starved) cool */
.cella[data-v="L"], .legenda .L { background: #f6cfc4; color: #6e2312; }
.scheda-pa .cella[data-v="H"], .legenda-pa .H { background: #c9dbf0; color: #173d66; }
.scheda thead th.secondaria { font-style: italic; }
.cella[data-v="D"], .legenda .D { background: #fbe6b6; color: #5c3d04; }
.cella[data-v="F"], .legenda .F { background: #f6cfc4; color: #6e2312; }
.cella[data-v="Y"], .legenda .Y { background: #f6cfc4; color: #6e2312; }
.esito-fine.esito-flow { font-family: inherit; }
.scheda thead th.nc, .legenda .nc i { font-style: italic; }
.scheda td.nc { background: var(--fondo2); }
.scheda td.nc .cella { border-style: dashed; }
.esito-fine { margin: .4rem 0 0; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
              font-size: .85rem; overflow-wrap: anywhere; color: var(--muto); }
.cella:focus-visible { outline: 2px solid var(--accento); outline-offset: 1px; }
.esito-scheda { margin: 1rem 0 0; font-weight: 600; min-height: 1.6em; }
.regole { max-width: 76ch; }
.regole li { margin-bottom: .5rem; }
.scheda-wrap { overflow-x: auto; }
/* IDEX alignment card: readings typed in, the fit, verdicts and firmware lines */
.solo-stampa { display: none; }
.scheda-idex th[scope="row"] { text-align: left; white-space: nowrap; font-weight: 600; }
.scheda-idex .idex-n { display: inline-block; min-width: 1.4rem; font-variant-numeric: tabular-nums; }
.scheda-idex td.temp input { width: 4.6rem; border-bottom: 1px dashed var(--muto); }
.scheda-idex td.temp input:disabled { opacity: .35; }
.scheda-idex td.fit, .scheda-idex td.res { font-variant-numeric: tabular-nums; font-size: .82rem; white-space: nowrap; }
.idex-cur { width: 4.6rem; font: inherit; font-size: .92rem; padding: .4rem .5rem; border-radius: 8px;
            border: 1px solid var(--filo); background: var(--carta); color: #16191d; }
.idex-esito { margin-top: 1.4rem; }
.idex-esito h3 { margin: 1.4rem 0 .5rem; }
.idex-offset { font-weight: 700; font-size: 1.08rem; }
.idex-termini th[scope="row"] { text-align: left; font-weight: 600; }
.idex-termini td { vertical-align: top; font-size: .9rem; }
.idex-termini small { color: var(--muto); }
.esito-ok, .esito-watch, .esito-fix { display: inline-block; padding: .05rem .5rem; border-radius: 5px; }
.esito-ok { background: #cfe8d3; color: #1e4a27; }
.esito-watch { background: #fbe6b6; color: #5c3d04; }
.esito-fix { background: #f6cfc4; color: #6e2312; }
.idex-cmd { font: .88rem/1.5 ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; background: var(--fondo2);
            border: 1px solid var(--filo); border-radius: 8px; padding: .7rem .9rem; overflow-x: auto; }
.idex-th1 { color: var(--muto); font-size: .9rem; }

@media (max-width: 1040px) {
  .pagina { display: block; }
  .indice { position: static; width: auto; height: auto; padding: 1rem 1.2rem;
            border-right: 0; border-bottom: 1px solid var(--filo); }
  .indice summary { display: block; cursor: pointer; font-weight: 600; padding: .3rem 0; }
  .indice[open] summary { margin-bottom: .6rem; }
  .marchio { margin: .2rem .2rem 1rem; }
  main { padding: 2rem 16px 4rem; }
  .testata { margin: -.8rem 0 1rem; }
  h1 { font-size: 1.85rem; }
  .corpo, .due { grid-template-columns: minmax(0, 1fr); gap: 1.2rem; }
  .schizzo { margin-left: 1.4rem; }
}
/* phones: the sketch goes above the intro, the column's full width, not
   floated; the text keeps the full width too */
@media (max-width: 640px) {
  .schizzo { float: none; width: 100%; max-width: none; margin: 0 0 1.2rem; }
}

/* Printing: the scorecard (and any guide page) without the contents, the
   language pill, the navigation or the photo briefs; the card on one sheet. */
@media print {
  :root { --fondo: #fff; --fondo2: #fff; --testo: #000; --muto: #333; --filo: #999; }
  body { font-size: 11pt; background: #fff; color: #000; }
  .indice, .testata, .avanti, .salta, .brief, .scheda-strumenti, .non-stampa { display: none !important; }
  /* every "More" prints open: the beforeprint handler opens them; where the
     browser knows ::details-content, CSS alone does it too (no JavaScript) */
  details.approfondisci::details-content { content-visibility: visible; display: block; }
  .approfondisci > summary { display: block; min-height: 0; padding: 0; border: 0; background: none;
                             color: #333; font-size: 8.5pt; letter-spacing: .08em; text-transform: uppercase; }
  .approfondisci > summary::before { display: none; }
  .approfondisci[open] > summary { margin-bottom: 1.5mm; }
  .approfondisci-corpo { border-left: 1px solid #999; margin-left: 0; }
  .pagina { display: block; }
  main { padding: 0; max-width: none; }
  .passo, .tabella, figure, .scheda tr { break-inside: avoid; }
  .schizzo { float: right; width: 32mm; margin: 0 0 2mm 5mm; color: #555; opacity: 1; }
  .cella { border: 1px solid #666; }
  .cella[data-v="-"] { background: #fff; color: #fff; }
  a { color: #000; text-decoration: none; }
  /* scorecard: rules on page 1, legend + the whole grid on page 2, sized to fit A4 portrait */
  .scorecard .legenda { break-before: page; margin-top: 0; font-size: 8.5pt; }
  .scheda-wrap { overflow: visible; }
  .scheda { table-layout: fixed; width: 100%; font-size: 8pt; break-inside: avoid; }
  .scheda th, .scheda td { padding: 1.2mm .6mm; }
  .scheda thead th { font-size: 6.5pt; letter-spacing: 0; text-transform: none; line-height: 1.15;
                     overflow-wrap: anywhere; hyphens: auto; }
  .scheda td.note { min-width: 0; width: 22mm; }
  .scheda td.temp input { width: 100%; font-size: 8pt; }
  .scheda tbody tr { height: 11mm; }
  .cella { width: 100%; height: 7.5mm; font-size: 8pt; border-radius: 1.5mm; }
  .esito-scheda, .esito-fine { font-size: 8.5pt; }
  .solo-stampa { display: block; font-size: 8.5pt; margin: 0 0 3mm; }
  .scheda-idex td.temp input { border-bottom: 0; }
  .scheda-idex td.fit, .scheda-idex td.res { font-size: 7pt; }
  .idex-esito { font-size: 8.5pt; }
  .idex-esito:empty { display: none; }
  /* the rules are long (Italian runs ~15 % longer): keep them on page 1 */
  .scorecard-idex h2 { margin: 4mm 0 2mm; }
  .scorecard-idex .regole { font-size: 9.5pt; line-height: 1.4; }
  .scorecard-idex .regole li { margin-bottom: 1.2mm; }
  .scheda-idex th[scope="row"] { white-space: normal; font-size: 7.5pt; }
}
@page { size: A4; margin: 12mm; }
"""
